package com.smartcampus.service;

import com.smartcampus.exception.ResourceNotFoundException;
import com.smartcampus.model.*;
import com.smartcampus.repository.NotificationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class NotificationService {

    @Autowired
    private NotificationRepository repo;

    /** Called by BookingService and TicketService */
    public void send(User recipient, String type, String msg) {
    Notification n = Notification.builder()
            .recipient(recipient)
            .type(type)
            .message(msg)
            .read(false) // Changed from .isRead to .read
            .build();
    repo.save(n);
}

    public List<Notification> getForUser(Long userId) {
        return repo.findByRecipientIdOrderByCreatedAtDesc(userId);
    }

    public Notification markRead(Long id) {
        Notification n = repo.findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Notification", "id", id));
        
        // Regular setter generated by Lombok for boolean isRead is setRead
        n.setRead(true);
        return repo.save(n);
    }

    public void markAllRead(Long userId) {
        List<Notification> list = repo.findByRecipientIdOrderByCreatedAtDesc(userId);
        list.forEach(n -> n.setRead(true));
        repo.saveAll(list);
    }

    public void delete(Long id) { 
        repo.deleteById(id); 
    }
}