spring:
  application:
    name: smart-campus-api

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_campus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

server:
  port: 8081