spring:
  application:
    name: smart-campus-api

  mongodb:
    uri: mongodb+srv://evon:EVON1234@cluster1.via4f4a.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster1
  
  # ADD THIS SECTION
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 163190998619-m2kb7ahfqg4tbr9f9fuqarmusutc9o0p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"

  data:
    mongodb:
      uri: mongodb+srv://evon:EVON1234@cluster1.via4f4a.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster1

server:
  port: 8081  # Keep it as 8081

app:
  jwt:
    secret: ${JWT_SECRET:SmartCampusJwtSecretKeyForDevOnlyMustBeLongEnough12345}
    expiration: ${JWT_EXPIRATION:86400000}
  security:
    admin-confirmation-code: ${ADMIN_CONFIRMATION_CODE:ADMIN2026}