spring:
  application:
    name: smart-campus-api
  
  # ADD THIS SECTION
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - email
              - profile

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_campus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081  # Keep it as 8081