spring.application.name=pafproject

# MongoDB Atlas Configuration
spring.mongodb.uri=mongodb+srv://evon:EVON1234@cluster1.via4f4a.mongodb.net/?appName=Cluster1&retryWrites=true&w=majority
spring.mongodb.database=smart_campus_db

# Server Configuration
server.port=8888

# Logging
logging.level.com.example.pafproject.catalogue=DEBUG
